const propertyData = [
  {
    title: "Houses with Backyard",
    properties: [
      {
        name: "Tabby Town",
        location: "Gunug Batu, Indonesia",
        image: "/images/Tabby.svg",
        description: "A cozy wooden house with a large backyard, ideal for families and pets.",
        price: "$120 per night",
        duration: "Minimum 2 nights stay",
        features: ["Free WiFi", "Swimming Pool", "Garden", "Parking Space"],
        popular: true,
      },
      {
        name: "Anggana",
        location: "Bogor, Indonesia",
        image: "/images/Anggaga.svg",
        description: "A modern villa with a spacious backyard and a relaxing outdoor area.",
        price: "$150 per night",
        duration: "Minimum 3 nights stay",
        features: ["BBQ Area", "Smart TV", "Private Pool"],
        popular: false,
      },
      {
        name: "Seattle Rain",
        location: "Jakarta, Indonesia",
        image: "/images/scattle.svg",
        description: "Elegant home with wooden finishing and beautiful surroundings.",
        price: "$130 per night",
        duration: "Minimum 1 night stay",
        features: ["24/7 Security", "Gym", "Air Conditioning"],
        popular: false,
      },
      {
        name: "Wooden Pit",
        location: "Wonosobo, Indonesia",
        image: "/images/wood.svg",
        description: "A rustic wooden retreat in the heart of nature.",
        price: "$110 per night",
        duration: "Minimum 2 nights stay",
        features: ["Mountain View", "Fireplace", "Outdoor Seating"],
        popular: false,
      },
    ],
  },
  {
    title: "Apartment with Kitchen",
    properties: [
      {
        name: "PS Wood",
        location: "Depok, Indonesia",
        image: "/images/Ps Wood.svg",
        description: "A stylish apartment with a fully-equipped kitchen and a modern design.",
        price: "$90 per night",
        duration: "Minimum 2 nights stay",
        features: ["Kitchen", "Balcony", "High-Speed Internet"],
        popular: false,
      },
      {
        name: "One Five",
        location: "Jakarta, Indonesia",
        image: "/images/One Five.svg",
        description: "Comfortable and spacious apartment near the city center.",
        price: "$100 per night",
        duration: "Minimum 3 nights stay",
        features: ["Washer", "City View", "Parking Space"],
        popular: false,
      },
      {
        name: "Minimal",
        location: "Bogor, Indonesia",
        image: "/images/Minimal1.svg",
        description: "Minimalist design with a warm and welcoming atmosphere.",
        price: "$80 per night",
        duration: "Minimum 1 night stay",
        features: ["Minimalist Decor", "Smart TV", "24/7 Concierge"],
        popular: true,
      },
      {
        name: "Stays Home",
        location: "Wonosobo, Indonesia",
        image: "/images/stays.svg",
        description: "Perfect for travelers looking for a home-like experience.",
        price: "$95 per night",
        duration: "Minimum 2 nights stay",
        features: ["Kitchen", "Netflix", "Coffee Maker"],
        popular: false,
      },
    ],
  },
  {
    title: "Hotel with Living Room",
    properties: [
      {
        name: "Green Park",
        location: "Tangerang, Indonesia",
        image: "/images/Green Park.svg",
        description: "A hotel with a spacious living room, perfect for relaxation.",
        price: "$120 per night",
        duration: "Minimum 1 night stay",
        features: ["Living Room", "Free WiFi", "Breakfast Included"],
        popular: true,
      },
      {
        name: "Podo Wae",
        location: "Madiun, Indonesia",
        image: "/images/Podo Waes.svg",
        description: "A comfortable hotel with a stylish living room.",
        price: "$100 per night",
        duration: "Minimum 1 night stay",
        features: ["Living Room", "Smart TV", "Room Service"],
        popular: false,
      },
      {
        name: "Silver Rain",
        location: "Bandung, Indonesia",
        image: "/images/Silver.svg",
        description: "A luxurious hotel with a modern living room.",
        price: "$150 per night",
        duration: "Minimum 1 night stay",
        features: ["Living Room", "Gym", "Spa"],
        popular: false,
      },
      {
        name: "Cashville",
        location: "Kemang, Indonesia",
        image: "/images/Cashville.svg",
        description: "A classic hotel with a cozy living room.",
        price: "$110 per night",
        duration: "Minimum 1 night stay",
        features: ["Living Room", "Parking Space", "Bar"],
        popular: false,
      },
    ],
  },
];

export default propertyData;
